version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console port
    volumes:
      - minio_data:/data # Usando volume nomeado
    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=CHANGEME123
    command: server /data --console-address ":9001"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Porta padrão do RabbitMQ
      - "15672:15672" # Porta do painel de administração
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # Porta SMTP
      - "8025:8025" # Interface web para visualizar os emails
    volumes:
      - mailhog_data:/data # Usando volume nomeado
    restart: unless-stopped

  postgresql:
    image: postgres:15
    container_name: postgresql
    ports:
      - "5430:5432" # Porta padrão do PostgreSQL
    environment:
      - POSTGRES_DB=poll_system_db
      - POSTGRES_USER=poll_user
      - POSTGRES_PASSWORD=poll_password
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379" # Porta padrão do Redis
    command: redis-server --appendonly yes --requirepass redis_password
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=redis_password
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  minio_data: # Define o volume nomeado
  rabbitmq_data: # Define o volume nomeado para o RabbitMQ
  mailhog_data: # Define o volume nomeado para o MailHog
  postgresql_data: # Define o volume nomeado para o PostgreSQL
  redis_data: # Define o volume nomeado para o Redis
